# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28511b960a3d1300615fe30f5827fcc26e8cc7af318f4d002fb4585df97225eb0568f650a5050050030650b199b39cb7a0a9becd44dc3788d63db35c3c543243

test:
  secret_key_base: a26f104b12e9de2d9528d74be33d738673b054859cac3f2f56517e397757d183071acca252d27f1654821604e0255cdf6655db35c69769b2be530399c8e0d863

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
